/********************************************************
 *                                                     * 
 * MNISTTMVAApplication.C                              * 
 * Written by Seungmok Lee                             * 
 * Seoul Nat'l Univ.                                   * 
 * Department of Physics and Astronomy                 * 
 * email: physmlee@gmail.com                           * 
 * git : https://github.com/physmlee/DLStudy           * 
 * Date: 2020.01.30                                    * 
 *                                                     * 
 * Tested Enviornment                                  * 
 *   Python		2.7                                    * 
 *   ROOT		6.18/04                                * 
 *   tensorflow	1.14.0                                 * 
 *   keras		2.3.1                                  * 
 * In Ubuntu 18.04 LTS                                 * 
 *                                                     * 
*********************************************************
 *                                                     * 
 *                   INSTRUCTION                       * 
 *                                                     * 
 * This macro is an example multiclass classifier      * 
 * application for MNIST dataset using TMVA methods.   * 
 * This macro loads the trained weight file, which     * 
 * must be generated by 'MNISTTMVA.C' macro before     * 
 * running. This macro evaluates the accuracy,         * 
 * applying all the MNIST dataset. If the data file is * 
 * not found, getenates dataset running                * 
 * 'MNISTtoROOT.py' python macro.                      * 
 *                                                     * 
 * Run this by typing                                  *
 *                                                     * 
 *   >> root MNISTTMVAApplication.C                    * 
 *                                                     * 
*********************************************************
 *                                                     * 
 * Reference                                           * 
 * [1] https://root.cern/doc/master/TMVAMulticlassApplication_8C_source.html
 *     TMVA Multiclass Application Example Code        * 
 * [2] https://github.com/root-project/root/blob/master/documentation/tmva/UsersGuide/TMVAUsersGuide.pdf
 *     TMVA 4 Users Guide for ROOT >= 6.12 Version     * 
 *                                                     * 
********************************************************/

#include <cstdlib>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "TFile.h"
#include "TTree.h"
#include "TString.h"
#include "TSystem.h"
#include "TROOT.h"
#include "TStopwatch.h"
#include "TH1F.h"

#include "TMVA/Tools.h"
#include "TMVA/Reader.h"

using namespace TMVA;

void MNISTTMVAApplication()
{
    // Check if trained weight file exists
    TString weightfilename = "./dataset/weights/TMVAMulticlass_MNISTTMVA.weights.xml";
    if (gSystem->AccessPathName(weightfilename))
    {
        printf("[Error]  Could not open weight file.\n");
        printf("[Error]  Please run 'MNISTTMVA.C' first.\n");
        printf("[Error]  Exit.\n");
        exit(1);
    }

    // Load MNIST dataset ROOT file
    TString datafilename = "./data/MNIST.root";
	if (gSystem->AccessPathName(datafilename))
	{
		printf("Could not open data file. Trying to download it...\n");
		if (gSystem->AccessPathName("./MNISTtoROOT.py"))
		{
			printf("Cannot find 'MNISTtoROOT.py' macro. Please download it from https://github.com/physmlee/DLStudy\n");
			printf("Exit.\n");
			exit(1);
		}
		Int_t runpy = (Int_t)system("python MNISTtoROOT.py");
		if (runpy == 127 || runpy == -1)
		{
			printf("Could not run 'MNISTtoROOT.py'. Exit.\n");
			exit(1);
		}
	}

	TFile *data = TFile::Open(datafilename, "READ");
	if (!data->IsOpen())
	{
		printf("Data file open error.\n");
		printf("Exit.\n");
		exit(1);
	}

    // Setup TMVA
    TMVA::Tools::Instance();
    TMVA::Reader *reader = new TMVA::Reader("Color:!Silent");

    // Register variables
    Int_t pixel = 28 * 28;  // number of pixels in one image
    Float_t image[28 * 28]; // space to be linked to image data
    Char_t branchname[10];

    for (Int_t i = 0; i < pixel; i++)
    {
        sprintf(branchname, "image%d", i);
        reader->AddVariable(branchname, &image[i]); // register all the 784 pixels as variable
    }

    // Book method and load weight file.
    TString methodName = "kDL";
    reader->BookMVA(methodName, weightfilename);

    // Load data trees
    Int_t nb_classes = 10; // number of classes
    TTree *traintree[10], *testtree[10];
    Char_t trainname[10], testname[10];

    for (Int_t i = 0; i < nb_classes; i++)
    {
        sprintf(trainname, "train%d", i);
        traintree[i] = (TTree *)data->Get(trainname); //  Load training trees
        sprintf(testname, "test%d", i);
        testtree[i]  = (TTree *)data->Get(testname);  // Load testing trees

        // Link branches to variables
        for (Int_t j = 0; j < pixel; j++)
        {
            sprintf(branchname, "image%d", j);
            traintree[i]->SetBranchAddress(branchname, &image[j]);
            testtree[i] ->SetBranchAddress(branchname, &image[j]);
        }
    }

    // Evaluate train/test accuracy
    Int_t trainErr = 0, testErr = 0, ans, eventnum;
    Float_t prob, maxprob;
    for (Int_t i = 0; i < nb_classes; i++)
    {
        printf("\n\n<<Class %d>>\n", i);
        printf("\tApplying to training data\n");
        eventnum = traintree[i]->GetEntries();
        for (Int_t event = 0; event < eventnum; event++)
        {
            cout << "\tProgress: " << event + 1 << " / " << eventnum << "\r"; // Show progress
            cout.flush();

            traintree[i]->GetEntry(event); // Get entry
            ans = 0;
            maxprob = 0;

            for (Int_t cand = 0; cand < nb_classes; cand++) // For all the candidates,
            {
                prob = reader->EvaluateMulticlass(methodName)[cand];
                ans = prob > maxprob ? cand : ans; // Which one has the largest probability?
                maxprob = prob > maxprob ? prob : maxprob; // With what probability?
            }

            if (ans != i) // If the answer is wrong...
            {
                trainErr++; // ... add 1 to trainErr
            }
        }

        printf("\n\tApplying to testing  data\n", i);
        eventnum = testtree[i]->GetEntries();
        for (Int_t event = 0; event < eventnum; event++)
        {
            cout << "\tProgress: " << event + 1 << " / " << eventnum << "\r"; // Show progress
            cout.flush();

            testtree[i]->GetEntry(event); // Get entry
            ans = 0;
            maxprob = 0;

            for (Int_t cand = 0; cand < nb_classes; cand++) // For all the candidates,
            {
                prob = reader->EvaluateMulticlass(methodName)[cand];
                ans = prob > maxprob ? cand : ans; // Which one has the largest probability?
                maxprob = prob > maxprob ? prob : maxprob; // With what probability?
            }

            if (ans != i) // If the answer is wrong...
                testErr++; // ... add 1 to testErr
        }
    }

    // Print the result
    printf("\n");
    printf("Train accuracy: %f\n", (Double_t)(60000 - trainErr) / 60000);
    printf("Test  accuracy: %f\n", (Double_t)(10000 - testErr ) / 10000);
}

// Code Ends Here
